//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeShop.Model
{
    using CoffeShop.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class BillInfo : BaseViewModel
    {
        private string _Id;
        private string _IdBill;
        private string _IdFood;
        private Nullable<int> _Count;
        private Nullable<Double> _TotalPrice;

        public string Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }
        public string IdBill { get => _IdBill; set { _IdBill = value; OnPropertyChanged(); } }
        public string IdFood { get => _IdFood; set { _IdFood = value; OnPropertyChanged(); } }
        public Nullable<int> Count { get => _Count; set { _Count = value; OnPropertyChanged(); } }
        public Nullable<Double> TotalPrice { get => _TotalPrice; set { _TotalPrice = value; OnPropertyChanged(); } }

        public virtual Bill Bill { get; set; }
        public virtual Food Food { get; set; }
    }
}
